# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build-test-check
# This workflow builds the different libraries the project has.
# The workflow is triggered on any PR and when pushing on main branch.
# It also can run manually if needed.

on:
  pull_request:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      name:
        description: 'Manual build-test-check trigger'
      home:
        description: 'location'
        required: false

jobs:
  build-test-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: clean
        run: ./gradlew clean
      - name: assemble debug
        run: ./gradlew assembleDebug
      - name: assemble release
        run: ./gradlew assembleRelease
      - name: unit tests
        run: ./gradlew testDebugUnitTest
      - name: build instrumentation tests
        run: ./gradlew assembleAndroidTest
      - name: lint
        run: ./gradlew lintDebug
      - name: ktlint
        run: ./gradlew ktlint
