# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: publish-wmutils-mavencentral
# This workflow builds and publishes in Maven Central the WM Utils artifact.
# Although the final publishing step has to be done manually in Sonatype site.

on:
  push:
    tags:
      - 'wmutils*'

  workflow_dispatch:
    inputs:
      name:
        description: 'Triggers publication to MavenCentral - WM Utils'
      home:
        description: 'location'
        required: false

jobs:
  publish-WMUtils-MavenCentral:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - name: Set up JDK 11
        uses: actions/setup-java@0f62d2ad8407a414cddd4790bed06fd9ebda0f56 # v1.4.5
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      # Base64 decodes and pipes the GPG key content into the secret file
      - name: Prepare environment
        env:
          SIGNING_SECRET_KEY: ${{ secrets.SIGNING_SECRET_KEY }}
          SIGNING_SECRET_FILE: ${{ secrets.SIGNING_SECRET_FILE }}
        run: |
          git fetch --unshallow
          sudo bash -c "echo '$SIGNING_SECRET_KEY' | base64 -d > '$SIGNING_SECRET_FILE'"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: clean
        run: ./gradlew :utils:wm-utils:clean

        # Builds the release artifacts of the library
      - name: Release build
        run: ./gradlew :utils:wm-utils:assembleRelease

        # Generates other artifacts
      - name: Source jar
        run: ./gradlew :utils:wm-utils:androidSourcesJar

      # Generates docs artifact
      - name: Docs jar
        run: ./gradlew :utils:wm-utils:dokkaHtmlJar

        # Runs upload to MavenCentral (final release step will be manually done in Sonatype site)
      - name: Publish to MavenCentral
        run: ./gradlew  :utils:wm-utils:publishSurfaceDuoSDKPublicationToMavencentralRepository --max-workers 1
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_FILE: ${{ secrets.SIGNING_SECRET_FILE }}

