# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: publish-bottomnavigation-mavencentral
# This workflow builds and publishes in Maven Central the BottomNavigation artifact.
# Although the final publishing step has to be done manually in Sonatype site.

on:
  push:
    tags:
      - 'bottomnavigation*'

  workflow_dispatch:
    inputs:
      name:
        description: 'Triggers publication to MavenCentral - BottomNavigation'
      home:
        description: 'location'
        required: false

jobs:
  publish-BottomNavigation-MavenCentral:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      # Base64 decodes and pipes the GPG key content into the secret file
      - name: Prepare environment
        env:
          SIGNING_SECRET_KEY: ${{ secrets.SIGNING_SECRET_KEY }}
          SIGNING_SECRET_FILE: ${{ secrets.SIGNING_SECRET_FILE }}
        run: |
          git fetch --unshallow
          sudo bash -c "echo '$SIGNING_SECRET_KEY' | base64 -d > '$SIGNING_SECRET_FILE'"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: clean
        run: ./gradlew :bottomnavigation:bottomnavigation:clean

        # Builds the release artifacts of the library
      - name: Release build
        run: ./gradlew :bottomnavigation:bottomnavigation:assembleRelease

        # Generates other artifacts
      - name: Source jar
        run: ./gradlew :bottomnavigation:bottomnavigation:androidSourcesJar

      # Generates docs artifact
      - name: Docs jar
        run: ./gradlew :bottomnavigation:bottomnavigation:dokkaHtmlJar

        # Runs upload to MavenCentral (final release step will be manually done in Sonatype site)
      - name: Publish to MavenCentral
        run: ./gradlew  :bottomnavigation:bottomnavigation:publishSurfaceDuoSDKPublicationToMavencentralRepository --max-workers 1
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_FILE: ${{ secrets.SIGNING_SECRET_FILE }}

