# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: publish-bintray
# This workflow (builds and) publishes the different libraries the project has.
# Publication gets triggered when a new release-tag is created (we also have manual publishing if needed).
# Every library publication has its own job, so if one fails the other can run, and we can see them all
# individually in Github Actions view.

on:
  push:
    tags:
      - 'bintray*'

  workflow_dispatch:
    inputs:
      name:
        description: 'Manual publication to bintray/jcenter - dualscreenSDK'
      home:
        description: 'location'
        required: false

jobs:
  build-test-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: clean
        run: ./gradlew clean
      - name: assemble debug
        run: ./gradlew assembleDebug
      - name: unit tests
        run: ./gradlew testDebugUnitTest
      - name: lint
        run: ./gradlew lintDebug
      - name: ktlint
        run: ./gradlew ktlint

  publish-screenmanager-core:
    needs: build-test-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: screenmanager-core publication
        env:
          BINTRAY_USER: ${{secrets.BINTRAY_USER}}
          BINTRAY_KEY: ${{secrets.BINTRAY_KEY}}
          BINTRAY_ORG: ${{secrets.BINTRAY_ORG}}
        run: ./gradlew :screenmanager:screenmanager-core:bintrayUpload

  publish-screenmanager-displaymask:
    needs: build-test-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: screenmanager-displaymask publication
        env:
          BINTRAY_USER: ${{secrets.BINTRAY_USER}}
          BINTRAY_KEY: ${{secrets.BINTRAY_KEY}}
          BINTRAY_ORG: ${{secrets.BINTRAY_ORG}}
        run: ./gradlew :screenmanager:dm:screenmanager-displaymask:bintrayUpload

  publish-screenmanager-windowmanager:
    needs: build-test-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: screenmanager-windowmanager publication
        env:
          BINTRAY_USER: ${{secrets.BINTRAY_USER}}
          BINTRAY_KEY: ${{secrets.BINTRAY_KEY}}
          BINTRAY_ORG: ${{secrets.BINTRAY_ORG}}
        run: ./gradlew :screenmanager:wm:screenmanager-windowmanager:bintrayUpload

  publish-screenmanager-utils:
    needs: build-test-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: screenmanager-utils publication
        env:
          BINTRAY_USER: ${{secrets.BINTRAY_USER}}
          BINTRAY_KEY: ${{secrets.BINTRAY_KEY}}
          BINTRAY_ORG: ${{secrets.BINTRAY_ORG}}
        run: ./gradlew :screenmanager:screenmanager-utils:bintrayUpload

  publish-layouts:
    needs: build-test-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: layouts publication
        env:
          BINTRAY_USER: ${{secrets.BINTRAY_USER}}
          BINTRAY_KEY: ${{secrets.BINTRAY_KEY}}
          BINTRAY_ORG: ${{secrets.BINTRAY_ORG}}
        run: ./gradlew :layouts:layouts:bintrayUpload

  publish-fragmentshandler:
    needs: build-test-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: fragmentshandler publication
        env:
          BINTRAY_USER: ${{secrets.BINTRAY_USER}}
          BINTRAY_KEY: ${{secrets.BINTRAY_KEY}}
          BINTRAY_ORG: ${{secrets.BINTRAY_ORG}}
        run: ./gradlew :fragmentshandler:fragmentshandler:bintrayUpload

  publish-bottomnavigation:
    needs: build-test-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: bottomnavigation publication
        env:
          BINTRAY_USER: ${{secrets.BINTRAY_USER}}
          BINTRAY_KEY: ${{secrets.BINTRAY_KEY}}
          BINTRAY_ORG: ${{secrets.BINTRAY_ORG}}
        run: ./gradlew :bottomnavigation:bottomnavigation:bintrayUpload

  publish-tabs:
    needs: build-test-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: tabs publication
        env:
          BINTRAY_USER: ${{secrets.BINTRAY_USER}}
          BINTRAY_KEY: ${{secrets.BINTRAY_KEY}}
          BINTRAY_ORG: ${{secrets.BINTRAY_ORG}}
        run: ./gradlew :tabs:tabs:bintrayUpload

  publish-recyclerview:
    needs: build-test-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: recyclerview publication
        env:
          BINTRAY_USER: ${{secrets.BINTRAY_USER}}
          BINTRAY_KEY: ${{secrets.BINTRAY_KEY}}
          BINTRAY_ORG: ${{secrets.BINTRAY_ORG}}
        run: ./gradlew :recyclerview:recyclerview:bintrayUpload
